name: Deployment

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

jobs:
  deployment:
    runs-on: ubuntu-20.04
    environment: production
    concurrency: production
    steps:
    - name: Clone Repository (Latest)
      uses: actions/checkout@v3
      if: github.event.inputs.git-ref == ''
    - name: Clone Repository (Custom Ref)
      uses: actions/checkout@v3
      if: github.event.inputs.git-ref != ''
      with:
        ref: ${{ github.event.inputs.git-ref }}
    - name: Build binary
      run: cargo build --release
    - name: Run deploy branch playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yml
        directory: ./contrib/ansible
        key: ${{secrets.SSH_PRIVATE_KEY}}
        vault_password: ${{secrets.VAULT_PASSWORD}}
        options: |
          --verbose
